# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d79451c8ea5efa19f51b10ec0c55c01148c3b9597741fc44df1582c7d7cf37a66993157ff68c140e172f6a4dace5a357114ebe657d82e691474c7cca98b13136

test:
  secret_key_base: b5607ec59a897252a16d84c7eb0ca68020fbc72f83ab0a81fbe4c7a51f8ed8cc11d7abd831301f8cd82a9c631b085db909d235861c6079c714b299ef03534fc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
